language: go
branches:
  only:
    - master
go:
  - 1.x
  - 1.6
  - 1.7.x
  - master
go:
  - 1.7
  - 1.8
os:
  - linux
  - osx
env:
  - TERM=xterm-256color
  - GOTTY_PORT=8080
  - GOTTY_ADDRESS=127.0.0.1
sudo: required
dist: trusty
script:
  - make tools
  - make test
